services:
  map-manager:
    build:
      context: ./map-manager
      dockerfile: Dockerfile
    container_name: gis-map-manager
    image: map-manager:alpha
    environment:
      DATA_DIR: /app/data
      PORT: 4002
    ports:
      - "4002:4002"
    volumes:
      - ./data:/app/data

  terrain-calculator:
    build:
      context: ./terrain-calculator
      dockerfile: Dockerfile
    container_name: gis-terrain-calculator
    environment:
      DATA_DIR: /app/data
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

  map-manager-ui:
    build:
      context: ./map-manager-ui
      dockerfile: Dockerfile
    container_name: gis-map-manager-ui
    image: map-manager-ui:alpha
    environment:
      PORT: 5173
      VITE_PROXY_TARGET: http://map-manager:4002
    depends_on:
      - map-manager
    ports:
      - "5173:5173"

  map-provider:
    build:
      context: ./map-provider
      dockerfile: Dockerfile
    container_name: gis-map-provider
    image: map-provider:alpha
    environment:
      PORT: 8003
      DATA_DIR: /app/data
      PUBLIC_BASE_URL: http://localhost:8003
    # depends_on:
    #   - map-manager
    ports:
      - "8003:8003"
    volumes:
      - ./data:/app/data

  hat-provider:
    build:
      context: ./hat-provider
      dockerfile: Dockerfile
    container_name: gis-hat-provider
    image: hat-provider:alpha
    environment:
      PORT: 8004
      DATA_DIR: /app/data
    # depends_on:
    #   - map-manager
    ports:
      - "8004:8004"
    volumes:
      - ./data:/app/data

  example-client:
    build:
      context: ./example-client
      dockerfile: Dockerfile
      args:
        VITE_MAP_PROVIDER_BASE_URL: /map-provider-api
        VITE_HAT_PROVIDER_BASE_URL: /hat-provider-api
        VITE_MAP_URL: /map-provider-api/wmts?SERVICE=WMTS&REQUEST=GetCapabilities
    container_name: gis-example-client
    image: example-client:alpha
    environment:
      PORT: 4174
    depends_on:
      - map-provider
      - hat-provider
    ports:
      - "4174:4174"
