services:
  map-manager:
    build:
      context: ./map-manager
      dockerfile: Dockerfile
    container_name: gis-map-manager
    environment:
      DATA_DIR: /app/data
      PORT: 4002
    ports:
      - "4002:4002"
    volumes:
      - ./data:/app/data

  # terrain-calculator:
  #   build:
  #     context: ./terrain-calculator
  #     dockerfile: Dockerfile
  #   container_name: gis-terrain-calculator
  #   environment:
  #     DATA_DIR: /app/data
  #     PORT: 8000
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - ./data:/app/data

  map-manager-ui:
    build:
      context: ./map-manager-ui
      dockerfile: Dockerfile
    container_name: gis-map-manager-ui
    environment:
      PORT: 5173
      VITE_PROXY_TARGET: http://map-manager:4002
    depends_on:
      - map-manager
    ports:
      - "5173:5173"

  map-provider:
    build:
      context: ./map-provider
      dockerfile: Dockerfile
    container_name: gis-map-provider
    image: map-provider:alpha
    environment:
      PORT: 8003
      DATA_DIR: /app/data
    depends_on:
      - map-manager
    ports:
      - "8003:8003"
    volumes:
      - ./data:/app/data

  hat-provider:
    build:
      context: ./hat-provider
      dockerfile: Dockerfile
    container_name: gis-hat-provider
    environment:
      PORT: 8004
      DATA_DIR: /app/data
    depends_on:
      - map-manager
    ports:
      - "8004:8004"
    volumes:
      - ./data:/app/data

  example-client:
    build:
      context: ./example-client
      dockerfile: Dockerfile
    container_name: gis-example-client
    environment:
      PORT: 4174
      MAP_PROVIDER_PROXY_TARGET: http://map-provider:8003
      HAT_PROVIDER_PROXY_TARGET: http://hat-provider:8004
    depends_on:
      - map-provider
      - hat-provider
    ports:
      - "4174:4174"
